name = "Spectrum Galaxy"
author = "SGMT"
version = "1.1.0-rc3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbf03086816170fb80e6fd9fb1987e2aa363cf648d6bec83e83a781d312a92e8"

[versions]
fabric = "0.14.13"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18"]
