name = "Spectrum Galaxy"
author = "SGMT"
version = "1.2.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f83e11f46ae882c52d6816f4297cd65e9bff305908b8dd47ca4d63c193f500bf"

[versions]
fabric = "0.14.22"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18"]
