name = "Spectrum Galaxy"
author = "SGMT"
version = "1.1.0-rc3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a579e925d84f717f4bef228d60d215e7fe5e6c22e9a785951a07f7ae97f6b0ab"

[versions]
fabric = "0.14.13"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18"]
