name = "Spectrum Galaxy"
author = "SGMT"
version = "1.1.0-rc3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "79804cb99cefbf0288fb3701771e111d664114bc2de4fa338d8063eda0f73135"

[versions]
fabric = "0.14.13"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18.2", "1.18"]
