name = "Spectrum Galaxy"
author = "SGMT"
version = "1.1.0-rc3"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c1ffce52dee161a87f451cf629a30f5d5766b829c0431e75882b6299fcb604d2"

[versions]
fabric = "0.14.8"
minecraft = "1.18.2"

[options]
acceptable-game-versions = ["1.18", "1.18-19.0.0"]
